services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - ./apps/auth/.env

  mongo-server:
    image: mongo
    logging:
      driver: none

  rmq-server:
    image: rabbitmq
    logging:
      driver: none

  redis-server:
    image: redis
    logging:
      driver: none
