services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo-server
      - rmq-server

  teams:
    build:
      context: .
      dockerfile: ./apps/teams/Dockerfile
      target: development
    command: npm run start:dev teams
    ports:
      - '8082:8082'
    volumes:
      - .:/app
    env_file:
      - ./apps/teams/.env
    depends_on:
      - mongo-server
      - rmq-server

  chats:
    build:
      context: .
      dockerfile: ./apps/chats/Dockerfile
      target: development
    command: npm run start:dev chats
    ports:
      - '8083:8083'
      - '8085:8085'
    volumes:
      - .:/app
    env_file:
      - ./apps/chats/.env
    depends_on:
      - mongo-server
      - rmq-server

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    ports:
      - '8081:8081'
      - '8084:8084'
    volumes:
      - .:/app
    env_file:
      - ./apps/notifications/.env
    depends_on:
      - mongo-server
      - rmq-server

  mongo-server:
    image: mongo
    logging:
      driver: none

  rmq-server:
    image: rabbitmq
    logging:
      driver: none

  redis-server:
    image: redis
    logging:
      driver: none
